
service: gcs-service

provider:
  name: aws
  runtime: nodejs8.10

functions:
  CreateDatabase:
    handler: handler.createDatabase
    events:
      - http: GET createDatabase
  # WORK ORDERS
  CreateWorkOrder:
    handler: handler.createWorkOrder
    events:
      - http: POST workorder
  # VEHICLES
  CreateVehicle:
    handler: handler.createVehicle
    events:
      - http: POST vehicle
  GetVehicleByPlate:
    handler: handler.getVehicleByPlate
    events:
      - http: GET vehicle/{plate}
        request:
            parameters:
              paths:
                plate: true
  # OWNERS
  CreateOwner:
    handler: handler.createOwner
    events:
      - http: POST owner
  AddWork:
    handler: handler.addWork
    events:
      - http: POST work

plugins:
  - serverless-offline